### PR TITLE
project finished

### PR DESCRIPTION
**Pull request by VocalNight**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@VocalNight Thanks for submitting! Quick question? What's a scenario where logs would be added to the DB? I've tried things like deleting a record manually in the database and then trying delete or update them (previously loaded), but nothing was recorded.

**Comment by TheCSharpAcademy** [comment]
@VocalNight Let me know if you need help 😊

**Comment by VocalNight** [comment]
I'll double check it

**Comment by VocalNight** [comment]
Should be good now.
Logs log when you access the movie page, edit,delete,create a movie and a few of the form errors when registering a user.

image

**Pull request merged**
